# Generated by Django 3.1.1 on 2020-09-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_number', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('date_of_enrollment', models.DateField()),
                ('year_of_birth', models.DateField()),
                ('boat_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('boat_number', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('number_of_detainees', models.IntegerField()),
            ],
        ),
    ]
